version: 2

sources:
  - name: operational_system
    schema: public
    tables:
      - name: src_subscriptions
        description: "E-mail subscriptions for notifications of upcoming garbage collections"
        columns:
          - name: email
            description: "E-mail of a subscription"
            tests:
              - dbt_expectations.expect_column_to_exist
              - not_null
          - name: location
            tests:
              - dbt_expectations.expect_column_to_exist
              - not_null
          - name: is_active
            tests:
              - dbt_expectations.expect_column_distinct_values_to_be_in_set:
                  value_set: [ 'true' ]
        tests:
          - dbt_expectations.expect_compound_columns_to_be_unique:
              column_list: [ "email", "location" ]
              ignore_row_if: "any_value_is_missing"
          - dbt_expectations.expect_column_pair_values_A_to_be_greater_than_B:
              column_A: "when_updated"
              column_B: "when_created"
              or_equal: True
      - name: src_collections
