version: 2

sources:
  - name: operational_system
    schema: public
    tables:
      - name: subscription
        columns:
          - name: email
            tests:
              - dbt_expectations.expect_column_to_exist
              - not_null
        tests:
          - dbt_expectations.expect_compound_columns_to_be_unique:
              column_list: [ "email", "location" ]
              ignore_row_if: "any_value_is_missing"
